import type { Metadata } from "next";
import { ArrowUpRight, Check, MessageCircle } from "lucide-react";
import { PublicShell } from "@/components/marketing/public-shell";
import { whatsappUrl } from "@/lib/marketing-config";
import { capturePlatformLeadAction } from "./actions";

export const metadata: Metadata = { title: "Agendar demonstração", description: "Agende uma demonstração do NexaWi Academias." };

export default async function DemoPage({ searchParams }: { searchParams: Promise<{ enviado?: string; erro?: string; plano?: string }> }) {
  const query = await searchParams;
  return <PublicShell><main className="public-page"><section className="page-hero"><span className="eyebrow">DEMONSTRAÇÃO PERSONALIZADA</span><h1>Veja a operação<br/><span>funcionando por inteiro.</span></h1><p>Conte um pouco sobre sua academia. A NexaWi prepara uma conversa objetiva, baseada no seu número de alunos, unidades e estágio de gestão.</p></section><section className="demo-layout"><div className="demo-benefits"><h2>Em uma conversa, você verá:</h2>{["Site da academia conectado ao CRM","Alunos, planos, contratos e financeiro","Agenda, treinos, avaliações e acesso","Relatórios e operação multiunidade","Plano e implantação adequados ao seu cenário"].map(item=><p key={item}><Check size={17}/>{item}</p>)}<a className="outline-action" href={whatsappUrl()} target="_blank" rel="noreferrer"><MessageCircle size={17}/>Prefiro conversar no WhatsApp</a><small>Atendimento digital 24 horas, 7 dias por semana.</small></div><form className="demo-form" action={capturePlatformLeadAction}><input className="honeypot" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true"/><input type="hidden" name="interest" value={query.plano ? `Plano ${query.plano}` : "Demonstração da plataforma"}/>{query.enviado && <div className="form-success">Solicitação recebida. Nossa equipe entrará em contato.</div>}{query.erro && <div className="form-error">Não foi possível enviar agora. Revise os dados ou fale conosco no WhatsApp.</div>}<label>SEU NOME<input required minLength={2} name="full_name" placeholder="Nome completo"/></label><label>ACADEMIA<input name="business_name" placeholder="Nome da academia"/></label><div><label>E-MAIL<input type="email" name="email" placeholder="voce@academia.com.br"/></label><label>WHATSAPP<input name="phone" placeholder="(00) 00000-0000"/></label></div><div><label>UNIDADES<input type="number" min={1} max={999} name="units_count" defaultValue={1}/></label><label>ALUNOS<input type="number" min={0} name="students_count" placeholder="Quantidade aproximada"/></label></div><label className="consent-check"><input required type="checkbox"/>Autorizo o contato da NexaWi e confirmo que li a <a href="/privacidade">Política de Privacidade</a>.</label><button className="primary-action">Solicitar demonstração <ArrowUpRight size={18}/></button></form></section></main></PublicShell>;
}
