import { Dumbbell, ListPlus, Plus, UserRoundCheck } from "lucide-react";
import { requireOrganization } from "@/lib/auth/session";
import { createOperationalClient, shortDate } from "@/lib/supabase/operational";
import { addWorkoutItemAction, assignWorkoutAction, createExerciseAction, createWorkoutAction, updateWorkoutAssignmentAction } from "../operational-actions";
import { ActionForm } from "../action-form";
import { buttonClass, inputClass, PageTitle } from "../ui";

export default async function WorkoutsPage() {
  const context = await requireOrganization(); const organization = context.activeOrganization as unknown as { id: string }; const db = await createOperationalClient();
  const [{ data: exercises }, { data: workouts }, { data: members }, { data: assignments }] = await Promise.all([
    db.from("exercises").select("*").eq("organization_id", organization.id).eq("active", true).order("name"),
    db.from("workout_templates").select("id,name,goal,level,notes,items:workout_items(id,sequence,sets,reps,load_guidance,rest_seconds,exercise:exercises(name))").eq("organization_id", organization.id).eq("active", true).order("created_at", { ascending: false }),
    db.from("members").select("id,full_name").eq("organization_id", organization.id).eq("status", "active").order("full_name"),
    db.from("member_workouts").select("id,status,starts_on,ends_on,member:members(full_name),workout:workout_templates(name)").eq("organization_id", organization.id).order("created_at", { ascending: false }).limit(100),
  ]);
  return <>
    <PageTitle eyebrow="PRESCRIÇÃO E EVOLUÇÃO" title="Treinos" description="Biblioteca, montagem detalhada de fichas e prescrição individual." badge={`${assignments?.filter((item) => item.status === "active").length ?? 0} ATIVOS`} />
    <div className="mt-8 grid gap-4 xl:grid-cols-4">
      <section className="dashboard-panel p-5"><h2 className="flex gap-2 font-semibold"><Plus size={16} className="text-emerald-300" />Exercício</h2><ActionForm action={createExerciseAction} className="mt-4 grid gap-3"><input className={inputClass} required name="name" placeholder="Nome" /><input className={inputClass} name="muscle_group" placeholder="Grupo muscular" /><input className={inputClass} name="equipment" placeholder="Equipamento" /><textarea className={inputClass} name="instructions" placeholder="Instruções técnicas" /><button className={buttonClass}>Adicionar</button></ActionForm></section>
      <section className="dashboard-panel p-5"><h2 className="flex gap-2 font-semibold"><Dumbbell size={16} className="text-cyan-300" />Ficha</h2><ActionForm action={createWorkoutAction} className="mt-4 grid gap-3"><input className={inputClass} required name="name" placeholder="Nome da ficha" /><input className={inputClass} name="goal" placeholder="Objetivo" /><select className={inputClass} name="level"><option value="">Todos os níveis</option><option value="beginner">Iniciante</option><option value="intermediate">Intermediário</option><option value="advanced">Avançado</option></select><textarea className={inputClass} name="notes" placeholder="Orientações gerais" /><button className={buttonClass}>Criar ficha</button></ActionForm></section>
      <section className="dashboard-panel p-5"><h2 className="flex gap-2 font-semibold"><ListPlus size={16} className="text-emerald-300" />Montar ficha</h2><ActionForm action={addWorkoutItemAction} className="mt-4 grid gap-3"><select className={inputClass} required name="workout_id"><option value="">Ficha</option>{workouts?.map((workout) => <option key={workout.id} value={workout.id}>{workout.name}</option>)}</select><select className={inputClass} required name="exercise_id"><option value="">Exercício</option>{exercises?.map((exercise) => <option key={exercise.id} value={exercise.id}>{exercise.name}</option>)}</select><div className="grid grid-cols-3 gap-2"><input className={inputClass} name="sets" type="number" min="1" placeholder="Séries" /><input className={inputClass} name="reps" placeholder="Reps" /><input className={inputClass} name="rest_seconds" type="number" min="0" placeholder="Descanso" /></div><input className={inputClass} name="load_guidance" placeholder="Orientação de carga" /><button className={buttonClass}>Incluir exercício</button></ActionForm></section>
      <section className="dashboard-panel p-5"><h2 className="flex gap-2 font-semibold"><UserRoundCheck size={16} className="text-cyan-300" />Prescrever</h2><ActionForm action={assignWorkoutAction} className="mt-4 grid gap-3"><select className={inputClass} required name="member_id"><option value="">Aluno</option>{members?.map((member) => <option key={member.id} value={member.id}>{member.full_name}</option>)}</select><select className={inputClass} required name="workout_id"><option value="">Ficha</option>{workouts?.map((workout) => <option key={workout.id} value={workout.id}>{workout.name}</option>)}</select><div className="grid grid-cols-2 gap-2"><input className={inputClass} name="starts_on" type="date" aria-label="Início" /><input className={inputClass} name="ends_on" type="date" aria-label="Fim previsto" /></div><button className={buttonClass}>Atribuir treino</button></ActionForm></section>
    </div>
    <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">
      {workouts?.map((workout) => { const items = workout.items as unknown as Array<{ id: string; sequence: number; sets: number | null; reps: string | null; load_guidance: string | null; rest_seconds: number | null; exercise?: { name?: string } }>; return <article className="dashboard-panel p-5" key={workout.id}><Dumbbell size={18} className="text-emerald-300" /><h2 className="mt-4 font-semibold">{workout.name}</h2><p className="mt-1 text-[10px] text-emerald-50/35">{workout.goal || "Objetivo livre"} · {workout.level || "todos"}</p><div className="mt-4 grid gap-2">{items?.sort((a, b) => a.sequence - b.sequence).map((item) => <div className="rounded-lg bg-black/15 p-3 text-xs" key={item.id}><strong>{item.exercise?.name}</strong><span className="ml-2 text-emerald-300">{item.sets || "—"} × {item.reps || "—"}</span><small className="mt-1 block text-emerald-50/30">{item.load_guidance || "Carga orientada pelo professor"}{item.rest_seconds ? ` · ${item.rest_seconds}s` : ""}</small></div>)}</div></article>; })}
    </div>
    <section className="dashboard-panel mt-6 overflow-hidden"><header className="border-b border-emerald-100/10 p-5"><h2 className="font-semibold">Prescrições dos alunos</h2></header>{assignments?.length ? assignments.map((assignment) => { const member = assignment.member as unknown as { full_name?: string }; const workout = assignment.workout as unknown as { name?: string }; return <article className="grid gap-3 border-b border-emerald-100/[.06] p-4 last:border-0 md:grid-cols-[1fr_1fr_auto] md:items-center" key={assignment.id}><div><strong className="text-sm">{member?.full_name}</strong><span className="block text-[10px] text-emerald-50/35">{workout?.name}</span></div><span className="text-[10px] text-emerald-50/35">{shortDate(assignment.starts_on)} → {shortDate(assignment.ends_on)}</span><ActionForm action={updateWorkoutAssignmentAction} className="flex gap-2"><input type="hidden" name="assignment_id" value={assignment.id} /><select className={`${inputClass} py-2 text-[10px]`} name="status" defaultValue={assignment.status}><option value="active">Ativo</option><option value="completed">Concluído</option><option value="cancelled">Cancelado</option></select><button className="rounded-lg border border-cyan-300/20 px-3 text-[10px] font-bold text-cyan-200">Salvar</button></ActionForm></article>; }) : <p className="p-8 text-center text-xs text-emerald-50/30">Nenhum treino prescrito.</p>}</section>
  </>;
}
