import { ArrowRight, ArrowUpRight, Clock3, MessageSquarePlus, Pencil, Plus, Search, Target, UserRoundCheck } from "lucide-react";
import { requireOrganization } from "@/lib/auth/session";
import { createOperationalClient } from "@/lib/supabase/operational";
import { ActionForm } from "../action-form";
import { buttonClass, inputClass, PageTitle } from "../ui";
import { addLeadActivityAction, convertLeadAction, createLeadAction, updateLeadDetailsAction, updateLeadStatusAction } from "./actions";

type Lead = { id:string;full_name:string;email:string|null;phone:string|null;source:string;status:string;interest:string|null;notes:string|null;branch_id:string|null;next_action_at:string|null;created_at:string };
type Activity = { id:string;lead_id:string;type:string;content:string|null;created_at:string };
type Option = { id:string;name:string };
const stages = [["new","Novos"],["contacting","Em contato"],["experimental_scheduled","Experimental"],["proposal","Proposta"],["won","Ganhos"],["lost","Perdidos"]] as const;
const sources = [["manual","Manual"],["site","Site"],["whatsapp","WhatsApp"],["instagram","Instagram"],["indicacao","Indicação"],["trafego_pago","Tráfego pago"],["outro","Outro"]] as const;

export default async function CrmPage({ searchParams }: { searchParams: Promise<{ q?: string; source?: string }> }) {
  const query = await searchParams;
  const context = await requireOrganization();
  const organization = context.activeOrganization as unknown as { id:string };
  const db = await createOperationalClient();
  let leadsQuery = db.from("crm_leads").select("id,full_name,email,phone,source,status,interest,notes,branch_id,next_action_at,created_at").eq("organization_id",organization.id).order("created_at",{ascending:false});
  if (query.source && query.source !== "all") leadsQuery = leadsQuery.eq("source", query.source);
  if (query.q?.trim()) { const term = query.q.trim().replace(/[,%()]/g, ""); leadsQuery = leadsQuery.or(`full_name.ilike.%${term}%,email.ilike.%${term}%,phone.ilike.%${term}%,interest.ilike.%${term}%`); }
  const [{data},{data:plans},{data:branches},{data:activities}] = await Promise.all([
    leadsQuery.limit(250),
    db.from("membership_plans").select("id,name").eq("organization_id",organization.id).eq("active",true).order("name"),
    db.from("branches").select("id,name").eq("organization_id",organization.id).eq("status","active").order("name"),
    db.from("crm_activities").select("id,lead_id,type,content,created_at").eq("organization_id",organization.id).order("created_at",{ascending:false}).limit(300),
  ]);
  const leads = (data ?? []) as Lead[];
  const recentActivities = (activities ?? []) as Activity[];

  return <>
    <PageTitle eyebrow="COMERCIAL E CAPTAÇÃO" title="CRM" description="Do primeiro contato à matrícula, com histórico, responsável e próxima ação." badge={`${leads.length} LEADS`} />
    <section className="dashboard-panel mt-8 p-5">
      <div className="grid gap-6 xl:grid-cols-[1.4fr_.6fr]">
        <div><h2 className="flex items-center gap-2 font-semibold"><Plus size={17} className="text-emerald-300"/>Novo lead</h2><ActionForm action={createLeadAction} className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><input className={inputClass} required name="full_name" placeholder="Nome completo"/><input className={inputClass} name="email" type="email" placeholder="E-mail"/><input className={inputClass} name="phone" placeholder="WhatsApp"/><input className={inputClass} name="interest" placeholder="Interesse / plano"/><select className={inputClass} name="source">{sources.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select className={inputClass} name="branch_id"><option value="">Sem unidade</option>{(branches as Option[] | null)?.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><input className={inputClass} name="next_action_at" type="datetime-local" aria-label="Próxima ação"/><button className={buttonClass}>Adicionar <ArrowUpRight size={15}/></button></ActionForm></div>
        <div><h2 className="flex items-center gap-2 font-semibold"><Search size={17} className="text-cyan-300"/>Filtrar funil</h2><form className="mt-4 grid gap-3" method="get"><input className={inputClass} name="q" defaultValue={query.q} placeholder="Nome, contato ou interesse"/><select className={inputClass} name="source" defaultValue={query.source || "all"}><option value="all">Todas as origens</option>{sources.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button className="rounded-xl border border-cyan-300/20 px-4 py-3 text-xs font-bold text-cyan-200">Filtrar</button></form></div>
      </div>
    </section>
    <section className="mt-6 grid gap-3 xl:grid-cols-3">{stages.map(([status,label])=>{const stageLeads=leads.filter((lead)=>lead.status===status);return <article className="dashboard-panel min-h-48 p-4" key={status}><div className="flex items-center justify-between"><strong className="text-sm">{label}</strong><span className="rounded-full bg-emerald-300/10 px-2 py-1 text-[9px] font-bold text-emerald-300">{stageLeads.length}</span></div><div className="mt-4 grid gap-3">{stageLeads.map((lead)=>{
        const history=recentActivities.filter((activity)=>activity.lead_id===lead.id).slice(0,3);
        return <div className="rounded-xl border border-emerald-100/10 bg-black/15 p-3" key={lead.id}><div className="flex items-start justify-between"><div><strong className="text-sm">{lead.full_name}</strong><span className="block text-[10px] text-emerald-50/35">{lead.interest||"Interesse não informado"} · {lead.source}</span></div><Target size={14} className="text-cyan-300"/></div>{lead.phone&&<a className="mt-2 block text-[10px] text-emerald-300" href={`https://wa.me/${lead.phone.replace(/\D/g,"")}`} target="_blank" rel="noreferrer">WhatsApp · {lead.phone}</a>}{lead.next_action_at&&<span className="mt-2 flex items-center gap-1 text-[10px] text-amber-200"><Clock3 size={11}/>{new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(lead.next_action_at))}</span>}
          <ActionForm action={updateLeadStatusAction} className="mt-3 flex gap-2"><input type="hidden" name="lead_id" value={lead.id}/><select className={`${inputClass} min-w-0 flex-1 py-2 text-[10px]`} name="status" defaultValue={lead.status}>{stages.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select><button className="rounded-lg border border-emerald-300/20 px-2 text-emerald-300" aria-label="Atualizar etapa"><ArrowRight size={14}/></button></ActionForm>
          <ActionForm action={addLeadActivityAction} className="mt-2 grid grid-cols-[.45fr_1fr_auto] gap-2"><input type="hidden" name="lead_id" value={lead.id}/><select className={`${inputClass} min-w-0 py-2 text-[10px]`} name="type"><option value="note">Nota</option><option value="call">Ligação</option><option value="whatsapp">WhatsApp</option><option value="email">E-mail</option><option value="visit">Visita</option><option value="follow_up">Retorno</option></select><input className={`${inputClass} min-w-0 py-2 text-[10px]`} name="content" placeholder="Registrar interação"/><button className="rounded-lg border border-cyan-300/20 px-2 text-cyan-300" aria-label="Adicionar interação"><MessageSquarePlus size={14}/></button></ActionForm>
          <details className="mt-2 rounded-lg border border-white/5 p-2"><summary className="flex cursor-pointer items-center gap-2 text-[10px] font-bold text-cyan-200"><Pencil size={12}/>Editar e ver histórico</summary><ActionForm action={updateLeadDetailsAction} className="mt-3 grid gap-2"><input type="hidden" name="lead_id" value={lead.id}/><input className={`${inputClass} py-2 text-[10px]`} name="full_name" defaultValue={lead.full_name} required/><input className={`${inputClass} py-2 text-[10px]`} name="email" type="email" defaultValue={lead.email||""} placeholder="E-mail"/><input className={`${inputClass} py-2 text-[10px]`} name="phone" defaultValue={lead.phone||""} placeholder="WhatsApp"/><input className={`${inputClass} py-2 text-[10px]`} name="interest" defaultValue={lead.interest||""} placeholder="Interesse"/><div className="grid grid-cols-2 gap-2"><select className={`${inputClass} py-2 text-[10px]`} name="source" defaultValue={lead.source}>{sources.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select><select className={`${inputClass} py-2 text-[10px]`} name="branch_id" defaultValue={lead.branch_id||""}><option value="">Sem unidade</option>{(branches as Option[] | null)?.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></div><input className={`${inputClass} py-2 text-[10px]`} name="next_action_at" type="datetime-local" defaultValue={lead.next_action_at?.slice(0,16)||""}/><textarea className={`${inputClass} text-[10px]`} name="notes" defaultValue={lead.notes||""} placeholder="Observações gerais"/><button className="rounded-lg bg-cyan-300/10 py-2 text-[10px] font-bold text-cyan-200">Salvar detalhes</button></ActionForm>{history.length>0&&<div className="mt-3 grid gap-2 border-t border-white/5 pt-3">{history.map(activity=><div key={activity.id} className="text-[9px] text-emerald-50/40"><strong className="text-emerald-200">{activity.type}</strong> · {activity.content}<span className="block opacity-60">{new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(activity.created_at))}</span></div>)}</div>}</details>
          {status!=="won"&&<ActionForm action={convertLeadAction} className="mt-2 grid grid-cols-2 gap-2"><input type="hidden" name="lead_id" value={lead.id}/><select className={`${inputClass} py-2 text-[10px]`} name="plan_id"><option value="">Sem plano</option>{(plans as Option[] | null)?.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select className={`${inputClass} py-2 text-[10px]`} name="branch_id"><option value="">Unidade</option>{(branches as Option[] | null)?.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="col-span-2 flex items-center justify-center gap-2 rounded-lg bg-emerald-300/10 py-2 text-[10px] font-bold text-emerald-300"><UserRoundCheck size={13}/>Converter em aluno</button></ActionForm>}
        </div>})}{!stageLeads.length&&<p className="py-5 text-xs text-emerald-50/25">Nenhum lead nesta etapa.</p>}</div></article>})}</section>
  </>;
}
