import { ShieldCheck, UserRound, UserRoundPlus } from "lucide-react";
import { requireOrganization } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";

export default async function TeamPage() {
  const context = await requireOrganization();
  const organization = context.activeOrganization as unknown as { id: string };
  const supabase = await createClient();
  const { data: memberships } = await supabase.from("organization_memberships").select("id, status, profile:profiles(id, full_name, phone), membership_roles(role:roles(code, name), branch:branches(name))").eq("organization_id", organization.id).order("created_at");

  return <><header className="flex items-end justify-between gap-4"><div><span className="text-[10px] font-bold tracking-[.16em] text-emerald-300">ACESSO E PERMISSÕES</span><h1 className="mt-2 text-4xl font-semibold tracking-[-.05em]">Equipe</h1><p className="mt-2 text-sm text-emerald-50/40">Papéis normalizados e preparados para escopo por unidade.</p></div><button disabled title="Convites serão habilitados na próxima etapa" className="hidden h-11 items-center gap-2 rounded-full bg-emerald-300 px-4 text-xs font-bold text-emerald-950 opacity-55 sm:flex"><UserRoundPlus size={16} /> Convidar</button></header><section className="dashboard-panel mt-8 overflow-hidden"><div className="grid grid-cols-[1fr_auto] border-b border-emerald-100/10 px-5 py-4 text-[9px] font-bold tracking-[.12em] text-emerald-50/30 sm:grid-cols-[1.2fr_1fr_1fr_auto]"><span>PROFISSIONAL</span><span className="hidden sm:block">FUNÇÃO</span><span className="hidden sm:block">ESCOPO</span><span>STATUS</span></div>{memberships?.map((membership) => { const profile = membership.profile as unknown as { full_name?: string } | null; const assignment = (membership.membership_roles as unknown as Array<{ role?: { name?: string }; branch?: { name?: string } | null }>)[0]; return <article key={membership.id} className="grid grid-cols-[1fr_auto] items-center border-b border-emerald-100/[.06] px-5 py-4 last:border-0 sm:grid-cols-[1.2fr_1fr_1fr_auto]"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-emerald-300/10 text-emerald-300"><UserRound size={16} /></span><strong className="text-sm">{profile?.full_name || "Usuário"}</strong></div><span className="hidden text-xs text-emerald-50/50 sm:block">{assignment?.role?.name || "Sem função"}</span><span className="hidden text-xs text-emerald-50/35 sm:block">{assignment?.branch?.name || "Toda a organização"}</span><span className="flex items-center gap-2 text-[9px] font-bold text-emerald-300"><ShieldCheck size={13} />{membership.status.toUpperCase()}</span></article>; })}</section></>;
}
