import type { Metadata } from "next";
import { ArrowUpRight, Check, Minus, Sparkles } from "lucide-react";
import Link from "next/link";
import { PublicShell, SectionHeading } from "@/components/marketing/public-shell";
import { getPlatformSiteSettings } from "@/lib/platform-site";

export const metadata: Metadata = { title: "Planos e preços", description: "Compare preços, limites e recursos dos planos NexaWi Academias." };

const rows = [
  ["Site público e captação", true, true, true], ["Alunos, planos e matrículas", true, true, true], ["Agenda, treinos e avaliações", true, true, true], ["Financeiro e inadimplência", true, true, true], ["CRM completo e histórico", false, true, true], ["Contratos e retenção", false, true, true], ["Multiunidade", false, true, true], ["Permissões por unidade", false, true, true], ["Visão consolidada da rede", false, false, true], ["Domínio personalizado", false, false, true], ["Suporte prioritário", false, false, true],
] as const;

export default async function PlansPage() {
  const { plans } = await getPlatformSiteSettings();
  return <PublicShell><main className="public-page"><section className="page-hero centered"><span className="eyebrow">PREÇO CLARO. EVOLUÇÃO REAL.</span><h1>Comece com a base.<br/><span>Cresça sem trocar de sistema.</span></h1><p>Todos os planos têm 7 dias de teste. Compare capacidade, implantação e recursos antes de escolher.</p></section><section className="plan-grid">{plans.map(plan=><article className={plan.featured?"plan-card featured":"plan-card"} key={plan.slug}>{plan.featured&&<span className="plan-label"><Sparkles size={13}/> MAIS ESCOLHIDO</span>}<span className="plan-index">NEXAWI / {plan.name.toUpperCase()}</span><h2>{plan.name}</h2><strong className="plan-audience">{plan.audience}</strong><div className="marketing-price"><small>R$</small><strong>{plan.price}</strong><span>/mês</span></div><p>{plan.description}</p><div className="plan-limits"><span>{plan.units}</span><span>{plan.students}</span><span>Teste de {plan.trial}</span><span>{plan.setup}</span></div><ul>{plan.included.map(feature=><li key={feature}><Check size={16}/>{feature}</li>)}</ul><Link href={`/demonstracao?plano=${plan.slug}`}>Quero este plano <ArrowUpRight size={16}/></Link><small className="plan-contract">{plan.commitment}</small></article>)}</section><section className="comparison-section"><SectionHeading eyebrow="COMPARATIVO COMPLETO" title="O plano mais caro precisa entregar uma vantagem concreta." copy="A diferença está na capacidade, gestão multiunidade, governança e prioridade — não apenas no nome do plano."/><div className="comparison-table" role="table" aria-label="Comparativo de planos"><div className="comparison-row comparison-head" role="row"><span>Recurso</span>{plans.map(plan=><strong key={plan.slug}>{plan.name.replace("Plano ","")}</strong>)}</div>{rows.map(([feature,...values])=><div className="comparison-row" role="row" key={feature}><span>{feature}</span>{values.map((enabled,index)=><i key={`${feature}-${index}`} aria-label={enabled?"Incluído":"Não incluído"}>{enabled?<Check size={16}/>:<Minus size={16}/>}</i>)}</div>)}</div></section><section className="public-section centered"><SectionHeading eyebrow="ANTES DE CONTRATAR" title="Sem cobrança surpresa depois do teste." copy="Nesta fase, o teste é ativado com acompanhamento comercial e não gera cobrança automática. O checkout recorrente só será lançado com informação clara, cartão cadastrado e aceite expresso."/><Link className="outline-action" href="/demonstracao">Agendar demonstração <ArrowUpRight size={16}/></Link></section></main></PublicShell>;
}
