import type { Metadata } from "next";
import { LegalPage } from "@/components/marketing/legal-page";
import { company } from "@/lib/marketing-config";
export const metadata: Metadata = { title: "Política de Privacidade" };
export default function PrivacyPage(){return <LegalPage eyebrow="PRIVACIDADE E LGPD" title="Política de Privacidade" intro="Como a NexaWi coleta, utiliza, protege e compartilha dados pessoais em seu site e plataforma.">
  <h2>1. Quem somos e a quem esta política se aplica</h2><p>A {company.tradeName}, razão social {company.legalName}, CNPJ {company.taxId}, com sede em {company.city}/{company.state}, trata dados de visitantes, contatos comerciais, clientes, usuários autorizados e pessoas que interagem com seus canais.</p>
  <h2>2. Papéis no tratamento</h2><p>Nos dados institucionais, comerciais, contratuais e de suporte, a NexaWi atua como controladora. Nos dados de alunos, colaboradores e leads inseridos por uma academia cliente, a academia normalmente decide as finalidades e atua como controladora, enquanto a NexaWi opera a plataforma sob suas instruções. O contrato poderá detalhar situações específicas.</p>
  <h2>3. Dados tratados</h2><ul><li>Identificação e contato: nome, e-mail, telefone, cargo e empresa.</li><li>Conta e segurança: identificador, permissões, registros de acesso e auditoria.</li><li>Operação da academia: dados de alunos, matrícula, frequência, agenda, treino e avaliação, conforme os módulos utilizados.</li><li>Financeiro e contrato: plano, cobranças, pagamentos e documentos.</li><li>Navegação: IP, dispositivo, páginas acessadas e cookies, conforme consentimento.</li></ul>
  <h2>4. Finalidades e bases legais</h2><p>Usamos dados para responder solicitações e propostas; executar contratos e testes; autenticar usuários; fornecer suporte; prevenir fraude; manter segurança e auditoria; cumprir obrigações legais; melhorar o produto; e realizar marketing quando houver consentimento ou interesse legítimo devidamente avaliado. Quando aplicável, o titular poderá retirar consentimento sem afetar tratamentos anteriores.</p>
  <h2>5. Compartilhamento e transferências</h2><p>Dados podem ser tratados por provedores de hospedagem, banco de dados, autenticação, comunicação, pagamentos, monitoramento e suporte estritamente necessários. Atualmente a arquitetura utiliza serviços como Vercel e Supabase. Alguns fornecedores podem processar dados fora do Brasil; nesses casos buscamos salvaguardas contratuais e técnicas compatíveis com a LGPD.</p>
  <h2>6. Retenção e segurança</h2><p>Mantemos os dados pelo prazo necessário às finalidades informadas, à execução do contrato, à defesa de direitos e às obrigações legais. Aplicamos controle de acesso, isolamento por organização, registros de auditoria, criptografia em trânsito e práticas de desenvolvimento seguro. Nenhum ambiente é totalmente imune a incidentes; adotaremos os procedimentos legais de resposta e comunicação quando exigidos.</p>
  <h2>7. Dados sensíveis e menores</h2><p>A academia deve avaliar a necessidade e a base legal antes de registrar avaliações físicas ou informações relacionadas à saúde. Dados de crianças e adolescentes exigem cuidados específicos e participação do responsável legal quando aplicável. O cliente não deve inserir dados excessivos ou sem fundamento jurídico.</p>
  <h2>8. Direitos do titular</h2><p>Você pode solicitar confirmação, acesso, correção, anonimização, bloqueio, eliminação, portabilidade quando regulamentada, informação sobre compartilhamentos, revisão de decisões automatizadas e esclarecimentos sobre consentimento. A solicitação poderá exigir validação de identidade e, quando a academia for controladora, será encaminhada a ela.</p>
  <h2>9. Contato de privacidade</h2><p>Solicitações podem ser enviadas para <a href={`mailto:${company.email}`}>{company.email}</a>. Enquanto não houver encarregado formalmente nomeado e publicado, esse canal centraliza as demandas de privacidade.</p>
  <h2>10. Atualizações</h2><p>Esta política poderá ser atualizada para refletir mudanças legais, técnicas ou comerciais. A versão vigente e sua data permanecerão publicadas nesta página.</p>
</LegalPage>}
