import type { Metadata } from "next";
import { LegalPage } from "@/components/marketing/legal-page";
import { company } from "@/lib/marketing-config";
export const metadata: Metadata = { title: "Modelo de Contrato" };
export default function ContractPage(){return <LegalPage eyebrow="MINUTA COMERCIAL" title="Contrato de Prestação de Serviço SaaS" intro="Estrutura-base para formalizar plano, implantação, suporte e proteção de dados.">
  <p><strong>CONTRATADA:</strong> {company.legalName}, nome fantasia {company.tradeName}, CNPJ {company.taxId}, estabelecida em {company.city}/{company.state}, e <strong>CONTRATANTE:</strong> pessoa jurídica identificada na proposta comercial ou no aceite eletrônico.</p>
  <h2>1. Objeto e documentos vinculados</h2><p>Licença temporária de uso do software NexaWi Academias, implantação e suporte nos limites do plano escolhido. Integram o contrato a proposta, a ordem de serviço, os Termos de Uso, a Política de Privacidade e o anexo de tratamento de dados.</p>
  <h2>2. Quadro comercial a preencher</h2><ul><li>Plano: Básico, Extensão ou Rede.</li><li>Unidades e limite de alunos.</li><li>Mensalidade, vencimento e forma de pagamento.</li><li>Implantação: R$ 240 ou R$ 120 por unidade no Plano Rede.</li><li>Teste: 7 dias.</li><li>Permanência mínima: 6 meses.</li><li>Integrações, equipamentos e serviços adicionais.</li></ul>
  <h2>3. Implantação e aceite</h2><p>A implantação começa após entrega das informações necessárias e confirmação comercial. O cliente deve validar cadastros, identidade, domínio e integrações. Ajustes fora do escopo poderão gerar orçamento adicional.</p>
  <h2>4. Obrigações da NexaWi</h2><p>Disponibilizar os módulos contratados, manter controles razoáveis de segurança, prestar suporte conforme o plano, corrigir falhas reproduzíveis e permitir exportação tecnicamente disponível quando solicitada dentro do prazo contratual.</p>
  <h2>5. Obrigações do cliente</h2><p>Pagar os valores acordados, manter usuários e permissões atualizados, obter bases legais e consentimentos necessários, utilizar equipamentos e conexão compatíveis, não compartilhar acesso indevido e cooperar na implantação e suporte.</p>
  <h2>6. Vigência, permanência e cancelamento</h2><p>O contrato entra em vigor no aceite e permanece pelo período indicado. A permanência mínima é de 6 meses, salvo condição diversa na proposta. A versão final deve definir aviso prévio, eventual multa proporcional, tratamento de valores pagos e prazo de exportação.</p>
  <h2>7. Reajuste e tributos</h2><p>A periodicidade e o índice de reajuste serão preenchidos na contratação. Cada parte responde pelos tributos que a legislação lhe atribuir.</p>
  <h2>8. Proteção de dados</h2><p>As partes cumprem a LGPD. Para dados tratados por conta da academia, o cliente atua em regra como controlador e a NexaWi como operadora. O anexo deve definir finalidade, instruções, subprocessadores, segurança, incidentes, atendimento a titulares, retenção, devolução e eliminação.</p>
  <h2>9. Nível de serviço e suporte</h2><p>O recebimento de solicitações ocorre 24/7 pelo canal oficial. A versão assinada deve estabelecer disponibilidade-alvo, janelas de manutenção, classificação de severidade e prazos de primeira resposta compatíveis com cada plano.</p>
  <h2>10. Propriedade intelectual e confidencialidade</h2><p>Cada parte preserva seus ativos preexistentes. Informações técnicas, comerciais e pessoais não públicas devem ser protegidas e usadas somente para executar o contrato.</p>
  <h2>11. Responsabilidade e terceiros</h2><p>A versão final deve prever limites proporcionais de responsabilidade, exclusões legalmente permitidas e regras para indisponibilidade de internet, meios de pagamento, mensageria, catracas e demais terceiros não controlados pela NexaWi.</p>
  <h2>12. Assinatura eletrônica e foro</h2><p>O aceite eletrônico poderá registrar identidade, data, IP e versão contratual. Aplica-se a lei brasileira e, em relações empresariais, indica-se o foro de {company.city}/{company.state}, ressalvadas hipóteses obrigatórias.</p>
</LegalPage>}
